apiVersion: v2
name: scaffold
description: Scaffolding the components of the sigstore architecture

type: application

version: 0.4.5
keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: fulcio
    version: 2.0.0
    repository: https://sigstore.github.io/helm-charts
    condition: fulcio.enabled
  - name: rekor
    version: 1.0.3
    repository: https://sigstore.github.io/helm-charts
    condition: rekor.enabled
  - name: trillian
    version: 0.1.12
    repository: https://sigstore.github.io/helm-charts
    condition: trillian.enabled
  - name: ctlog
    version: 0.2.35
    repository: https://sigstore.github.io/helm-charts
    condition: ctlog.enabled
  - name: tuf
    version: 0.1.4
    repository: https://sigstore.github.io/helm-charts
    condition: tuf.enabled

annotations:
  artifacthub.io/license: Apache-2.0
