{{- if .Values.copySecretJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-binding
  namespace: {{ .Values.tuf.forceNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-rekor-binding
  namespace: {{ .Values.rekor.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
{{ include "tuf.namespace" .Subcharts.tuf | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-fulcio-binding
  namespace: {{ .Values.fulcio.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
{{ include "tuf.namespace" .Subcharts.tuf | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}-ctlog-binding
  namespace: {{ .Values.ctlog.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.copySecretJob.serviceaccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.copySecretJob.serviceaccount }}
{{ include "tuf.namespace" .Subcharts.tuf | indent 4 }}
{{- end }}