{{- if .Values.copySecretJob.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.copySecretJob.serviceaccount }}
{{ include "tuf.namespace" .Subcharts.tuf | indent 2 }}
{{- end }}